### ISSUE TITLE
isuee with running the bot

### ISSUE THREAD

**Issue by xDevGuru** [ZorgeR/chatgpt-telegram-bot#7]
i followed the steps and when i run the bot and try to use it no response or reply from the bot so what is the isuess here and how can i fix it ?

**Comment by ZorgeR** [comment]
Can you show logs?

**Comment by xDevGuru** [comment]
Nothing really shows in the console log, just: (2024-09-14 03:43:31,983 - telegram.ext.Application - INFO - Application started). Do I have to enable something? Because what I did was just download the requirements, fill in the information in the environment variables, and run the bot.

**Edit**

After trying it on WSL 2, it worked, and the bot replied. I don't know why, but for some reason, it didn't work on my Windows.

**Comment by xDevGuru** [comment]
### Issue Summary

1. **Chat Mode Issue**:
   - Both models respond with: 
     ```
     I’m based on the GPT-3 model. How can I help you today?
     ```

2. **Image Command Issue**:
   - The `/image` command works, but it uses DALL-E 2 only. I haven't figured out how to use DALL-E 3 yet.

3. **`/image_album` Command Error**:
   - When using the `/image_album` command, an error occurs:
     ```
     2024-09-14 11:58:09,586 - root - INFO - New image generation request received from user @aaaaaa (id: 0000000000)
     2024-09-14 11:58:11,804 - root - ERROR - ⚠️ _An error has occurred._ ⚠️
     Error code: 400 - {'error': {'code': 'invalid_size', 'message': 'The size is not supported by this model.', 'param': None, 'type': 'invalid_request_error'}}
     Traceback (most recent call last):
       File "/home/admin/chatbot/bot/openai_helper.py", line 336, in generate_image
         response = await self.client.images.generate(
       File "/home/admin/chatbot/venv/lib/python3.10/site-packages/openai/resources/images.py", line 521, in generate
         return await self._post(
       File "/home/admin/chatbot/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1816, in post
         return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
       File "/home/admin/chatbot/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1510, in request
         return await self._request(
       File "/home/admin/chatbot/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1611, in _request
         raise self._make_status_error_from_response(err.response) from None
     openai.BadRequestError: Error code: 400 - {'error': {'code': 'invalid_size', 'message': 'The size is not supported by this model.', 'param': None, 'type': 'invalid_request_error'}}
     ```

4. **`/image_portrait` Command Error**:
   - Similar to the `/image_album` command, the `/image_portrait` command also results in an error:
     ```
     2024-09-14 12:01:38,548 - root - INFO - New image generation request received from user @aaaaaa (id: 0000000000)
     2024-09-14 12:01:39,773 - root - ERROR - ⚠️ _An error has occurred._ ⚠️
     Error code: 400 - {'error': {'code': 'invalid_size', 'message': 'The size is not supported by this model.', 'param': None, 'type': 'invalid_request_error'}}
     Traceback (most recent call last):
       File "/home/admin/chatbot/bot/openai_helper.py", line 336, in generate_image
         response = await self.client.images.generate(
       File "/home/admin/chatbot/venv/lib/python3.10/site-packages/openai/resources/images.py", line 521, in generate
         return await self._post(
       File "/home/admin/chatbot/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1816, in post
         return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
       File "/home/admin/chatbot/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1510, in request
         return await self._request(
       File "/home/admin/chatbot/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1611, in _request
         raise self._make_status_error_from_response(err.response) from None
     openai.BadRequestError: Error code: 400 - {'error': {'code': 'invalid_size', 'message': 'The size is not supported by this model.', 'param': None, 'type': 'invalid_request_error'}}
     ```

5. **Text-to-Speech (TTS) Command Issue**:
   - The `/tts` command works, but I haven't been able to change the voice or model. I tried modifying the `.env` file but it didn't have any effect.

**Comment by ZorgeR** [comment]
for dall-e-3 and /image_portrait /image_albums use in env. this vars

    - IMAGE_MODEL=dall-e-3
    
also you can set:
    - IMAGE_QUALITY=standard
    - IMAGE_FORMAT=document  # for send without telegram compression
    - IMAGE_SIZE=1024x1024


for tts:
    - ENABLE_TTS_GENERATION=true
    - TTS_MODEL=tts-1
    - TTS_VOICE=fable  # voice

for vision models:
    - ENABLE_VISION=true
    - VISION_PROMPT="Describe image"
    - VISION_MAX_TOKENS=300


Do you use latest version?
![image](https://github.com/user-attachments/assets/dc0bcaef-4408-448e-9998-e75226f77049)

default in env:
    - OPENAI_MODEL=gpt-4o-mini
